import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './index.css'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App userData={{"name":"moonrise","emailId":"moons@gmail.com","phoneNo":"439534954","projects":[{"title":"agroNexus","description":"first experience","technologies":["React","Node.js","java"],"repoLink":"link","_id":"6757c8c760ba565439a27851"}],"resume":"","experiences":[{"companyName":"smac","logo":"http://res.cloudinary.com/dgthxi1sd/image/upload/v1733802962/evolumin/uxpmejhg1v73ugqx1rrp.jpg","role":"smac","description":"smac","technologies":["React","Node.js"],"duration":"2 months","_id":"6757c8c760ba565439a27852"}],"techStacks":["React","python","Node JS","Docker"],"contactDetails":["www.github.com","www.linkedin.com","www.twitter.com"],"codingProfiles":["www.leetcode.com","www.geeksforgeeks.org"],"certifications":["https://res.cloudinary.com/dgthxi1sd/image/upload/v1733530869/evolumin/jv0gl1tyqtccmvtu6auu.png","https://res.cloudinary.com/dgthxi1sd/image/upload/v1733530869/evolumin/jv0gl1tyqtccmvtu6auu.png","https://res.cloudinary.com/dgthxi1sd/image/upload/v1733530869/evolumin/jv0gl1tyqtccmvtu6auu.png"],"achievements":[{"title":"swanith","description":"swanithswanith","_id":"6757c8c760ba565439a27853"},{"title":"swanith","description":"swanithswanithswanith","_id":"6757c8c760ba565439a27854"},{"title":"swanith","description":"swanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanith","_id":"6757c8c760ba565439a27855"},{"title":"swanithswanithswanithswanith","description":"swanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanith","_id":"6757c8c760ba565439a27856"}],"about":"swanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanithswanith","profilePhoto":"http://res.cloudinary.com/dgthxi1sd/image/upload/v1733802939/evolumin/acmqdmiatgrxamjumvey.jpg","_id":"6757c8c760ba565439a27850","createdAt":"2024-12-10T04:51:19.269Z","updatedAt":"2024-12-10T04:51:19.269Z","__v":0}} />
  </StrictMode>,
)
